build:
  image: macielbombonato/docker-builder-android:latest
  command: gradle build --stacktrace
  volumes:
    - /etc/ssl/certs:/etc/ssl/certs
    - ./:/opt/app
    - ~/.m2:/root/.m2
    - ~/.gradle:/root/.gradle
